sudo: required
services:
- docker
env:
  global:
  - secure: 3CuhuMjww4SiB/TkgqcPT8bnk43wcc3DbOO3f3L5X84O1CdRH6aSz3hSoyYnIugifgo2wFF5Lgkuey58AlBsVlPfFksEoCjRJcKe1wGJkr76rRgUI3jtXAIwe4KvHJvUSzCAA2od2+4HKbwKfZuVqj6GkOxZcms2mV5xpC9won4HJC/ZnPqNi2PSAaHrNeJ71pBVFcXj5+LG1C7ERVsOVlljb243Tk2RFNzinRj6F0WoG9Z/MTwcwnhyluo59k8C0Vb+GgdzJY0ZZ6JxXhdLq01akYx3Ju/ler8RqMmIJRN9xRc9T/V3I3Mti5XOCLKsvixhiCLsbl0AV/lQSACCwXX4gZhdNMbUFpdG3GOWai6k/BW3RKP5TPPV9QoN3XJBIVkDZT5qCG/SUhtCvO55Rk6YOX0IN8kGgFHtF8j/7/s02d/Sat8NTPHxtPZaTJPlo/SGAMwhdVV3BEwWHuOrafzSTPFzF/jdkL64AKRe5PuNss/tIuTLH81shMN+TdvkKhUvvRdCURbr3GlD3GoAbHyHvOEixOYVc8xNf6BsgKXbX+O3Xo6OwC1ZMmvO8hqLgs8qTdl+OhIQ2ReeFjifwM/L2DRr8AoJf8BFldO2zQYQI2YsW7CYsqZP0ySfhYN00onvgG3eQP3F4cfkrkkLxA3S3NPaApSwJpDNJrrT7DU=
  - secure: VZfxIjvBZDaID4OEkjO4vTCsJKtcBxe7q7pal/yWyWYK31krwB0nZTNABDfbZQZR7ieeOMfUWKGDMXBPP/lGmNcv07ACb8+x0a6oZN1yNGreyis3IqEDPI5tNzN83/3E8jN/lmjGLfNKS/h6Sbn/Z+fI0SzuhdZxUI577J1l2qdu5J8RAEMl3MD7x7T3XjcO7sLRJdTKHmwVeu4eNjis7cg9hz7HpfCnpg5kstHqdsolLoetmper3hIdtUxU6Z0TG+SezObXQ1BsygKEH5pKF+YFUadYGWr+1aYE8SK9eLBRHh2STki/N57ulHd4r0amQ9kJ+njBP/RR2yM+yTmI+Yd4x7C97jEw+NkFy8RoF9WwTg8rTG2S/xDRDOvzQJHtYpZ8g0hzftBTpkvuuweDXWV6840SXVwE8hLVkZYchY2TSlFIKGGOz4Skbt/q9FbO353kXv+EkCv5Wve814IEOreh1lLPGXDuYiFXjhPGzXIaxyt/KsbyO/ntg3LJxp2V1/Wb0kOTKhxxrkWXn0COlkfnetCoM0UiasCmfDvC33eD4r1gDpcDs7nT769yU5V7APHK4KlB6keU3AuGZ6HK0cIxVrJwHDDItLKEAPQWkkq4wJUrQ+dxAxtF5jUASzv/nzzTOVI8IjGbrg2GaPUcrwmJ6aGxuBlRbkWCtJATVYM=

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install bash

before_script:
- echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
script:
- make push
